CAMERA_INDEX = 0

MOTION_THRESHOLD = 20
MIN_MOTION_AREA = 500

CAPTURE_WIDTH = 640
CAPTURE_HEIGHT = 480
CAPTURE_FPS = 30

PROCESSING_WIDTH = 320
PROCESSING_HEIGHT = 240

BLUR_KERNEL_SIZE = 5
RESIZE_BEFORE_GRAYSCALE = True
RESIZE_INTERPOLATION = "LINEAR"

MAX_CONSECUTIVE_READ_FAILURES = 30
READ_RETRY_DELAY_S = 0.05
READ_FAILURE_LOG_INTERVAL_S = 5.0
MAX_RECONNECT_ATTEMPTS = 3

FPS_LOG_INTERVAL_S = 5.0

EXIT_KEY = "q"

DEBUG = False
LOG_LEVEL = "INFO"
WINDOW_NAME = "Motion Detection"